function [trainedClassifier, validationAccuracy] = trainClassifier(trainingData)
% [trainedClassifier, validationAccuracy] = trainClassifier(trainingData)
% Returns a trained classifier and its accuracy. This code recreates the
% classification model trained in Classification Learner app. Use the
% generated code to automate training the same model with new data, or to
% learn how to programmatically train models.
%
%  Input:
%      trainingData: A table containing the same predictor and response
%       columns as those imported into the app.
%
%
%  Output:
%      trainedClassifier: A struct containing the trained classifier. The
%       struct contains various fields with information about the trained
%       classifier.
%
%      trainedClassifier.predictFcn: A function to make predictions on new
%       data.
%
%      validationAccuracy: A double representing the validation accuracy as
%       a percentage. In the app, the Models pane displays the validation
%       accuracy for each model.
%
% Use the code to train the model with new data. To retrain your
% classifier, call the function from the command line with your original
% data or new data as the input argument trainingData.
%
% For example, to retrain a classifier trained with the original data set
% T, enter:
%   [trainedClassifier, validationAccuracy] = trainClassifier(T)
%
% To make predictions with the returned 'trainedClassifier' on new data T2,
% use
%   [yfit,scores] = trainedClassifier.predictFcn(T2)
%
% T2 must be a table containing at least the same predictor columns as used
% during training. For details, enter:
%   trainedClassifier.HowToPredict

% Auto-generated by MATLAB on 10-May-2023 10:46:28


% Extract predictors and response
% This code processes the data into the right shape for training the
% model.
inputTable = trainingData;
predictorNames = {'flow_stats/Data_ClearanceFactor', 'flow_stats/Data_CrestFactor', 'flow_stats/Data_ImpulseFactor', 'flow_stats/Data_Mean', 'flow_stats/Data_RMS', 'flow_stats/Data_THD', 'pressure_stats/Data_CrestFactor', 'pressure_stats/Data_ImpulseFactor', 'pressure_stats/Data_Mean', 'pressure_stats/Data_RMS', 'pressure_stats/Data_THD', 'flow_ps_spec/Data_PeakAmp1', 'flow_ps_spec/Data_PeakAmp3', 'pressure_ps_spec/Data_PeakAmp1', 'pressure_ps_spec/Data_PeakAmp3'};
predictors = inputTable(:, predictorNames);
response = inputTable.faultCode;
isCategoricalPredictor = [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false];
classNames = categorical({'0'; '1'; '10'; '11'; '100'; '101'; '110'; '111'}, {'0' '1' '10' '11' '100' '101' '110' '111'});

% Train a classifier
% This code specifies all the classifier options and trains the classifier.
template = templateTree(...
    'MaxNumSplits', 81, ...
    'NumVariablesToSample', 5);
classificationEnsemble = fitcensemble(...
    predictors, ...
    response, ...
    'Method', 'Bag', ...
    'NumLearningCycles', 20, ...
    'Learners', template, ...
    'ClassNames', classNames);

% Create the result struct with predict function
predictorExtractionFcn = @(t) t(:, predictorNames);
ensemblePredictFcn = @(x) predict(classificationEnsemble, x);
trainedClassifier.predictFcn = @(x) ensemblePredictFcn(predictorExtractionFcn(x));

% Add additional fields to the result struct
trainedClassifier.RequiredVariables = {'flow_ps_spec/Data_PeakAmp1', 'flow_ps_spec/Data_PeakAmp3', 'flow_stats/Data_ClearanceFactor', 'flow_stats/Data_CrestFactor', 'flow_stats/Data_ImpulseFactor', 'flow_stats/Data_Mean', 'flow_stats/Data_RMS', 'flow_stats/Data_THD', 'pressure_ps_spec/Data_PeakAmp1', 'pressure_ps_spec/Data_PeakAmp3', 'pressure_stats/Data_CrestFactor', 'pressure_stats/Data_ImpulseFactor', 'pressure_stats/Data_Mean', 'pressure_stats/Data_RMS', 'pressure_stats/Data_THD'};
trainedClassifier.ClassificationEnsemble = classificationEnsemble;
trainedClassifier.About = 'This struct is a trained model exported from Classification Learner R2023a.';
trainedClassifier.HowToPredict = sprintf('To make predictions on a new table, T, use: \n  [yfit,scores] = c.predictFcn(T) \nreplacing ''c'' with the name of the variable that is this struct, e.g. ''trainedModel''. \n \nThe table, T, must contain the variables returned by: \n  c.RequiredVariables \nVariable formats (e.g. matrix/vector, datatype) must match the original training data. \nAdditional variables are ignored. \n \nFor more information, see <a href="matlab:helpview(fullfile(docroot, ''stats'', ''stats.map''), ''appclassification_exportmodeltoworkspace'')">How to predict using an exported model</a>.');

% Extract predictors and response
% This code processes the data into the right shape for training the
% model.
inputTable = trainingData;
predictorNames = {'flow_stats/Data_ClearanceFactor', 'flow_stats/Data_CrestFactor', 'flow_stats/Data_ImpulseFactor', 'flow_stats/Data_Mean', 'flow_stats/Data_RMS', 'flow_stats/Data_THD', 'pressure_stats/Data_CrestFactor', 'pressure_stats/Data_ImpulseFactor', 'pressure_stats/Data_Mean', 'pressure_stats/Data_RMS', 'pressure_stats/Data_THD', 'flow_ps_spec/Data_PeakAmp1', 'flow_ps_spec/Data_PeakAmp3', 'pressure_ps_spec/Data_PeakAmp1', 'pressure_ps_spec/Data_PeakAmp3'};
predictors = inputTable(:, predictorNames);
response = inputTable.faultCode;
isCategoricalPredictor = [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false];
classNames = categorical({'0'; '1'; '10'; '11'; '100'; '101'; '110'; '111'}, {'0' '1' '10' '11' '100' '101' '110' '111'});

% Perform cross-validation
partitionedModel = crossval(trainedClassifier.ClassificationEnsemble, 'KFold', 5);

% Compute validation predictions
[validationPredictions, validationScores] = kfoldPredict(partitionedModel);

% Compute validation accuracy
validationAccuracy = 1 - kfoldLoss(partitionedModel, 'LossFun', 'ClassifError');
