name: MATLAB Code Issues Check
on:
  push:
    branches: [ "main", "richardthe3rd/**" ]
    paths:
     - '**.m'
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]  
    paths:
     - '**.m'
  schedule:
    - cron: '43 21 * * 1'
  workflow_call: 
permissions:
  contents: read  
jobs:
  codeIssues:
    name: MATLAB Code Issues Check
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Cache MATLAB
        id: cache-matlab
        uses: actions/cache@v3
        with:
          path: ${{ runner.tool_cache }}/MATLAB
          key: r2023b

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
      
      - name: Run commands
        uses: matlab-actions/run-command@v2
        with:
          command: result = codeIssues({'./matlab', './docker/matlab'}), assert(isempty(result.Issues))
